
management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

feign:
  client:
    config:
      autmationClient:
        read-timeout: 2000
        connect-timeout: 1000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      automationCB:
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        slidingWindowSize: 4
        
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s